#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
umask(0000);

set_time_limit(0);

require __DIR__.'/../vendor/autoload.php';

use SunCat\Console\ApplicationExtra;

$application = new ApplicationExtra(__DIR__.'/../src/Command/');
$application->run();
